# .github/workflows/import.yml
name: import

on:
  schedule:
    - cron: "37 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/google-docs-to-github@v3
        with:
          google_drive_folder_id: 1h8vBtbVfgpT6neJnMc33vKVStjtChwbA_
