# .github/workflows/import.yml
name: import
env:
  github_branch: master

  github_directory: google_docs
     

  github_token: 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
     
  google_drive_folder_id: 1h8vBtbVfgpT6neJnMc33vKVStjtChwbA

on:
  schedule:
    - cron: "43 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/google-docs-to-github@v3
        with:
          google_drive_folder_id: 1h8vBtbVfgpT6neJnMc33vKVStjtChwbA_
