inputs:
    github_branch: master
    github_directory: google_docs
    github_token: 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
    google_drive_folder_id: 1h8vBtbVfgpT6neJnMc33vKVStjtChwbA

runs:
  using: composite
  steps:
    - uses: r7kamura/google-docs-to-markdown@v0
      with:
        google_drive_folder_id: ${{ inputs.google_drive_folder_id }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        destination_dir: ${{ inputs.github_directory }}
        disable_nojekyll: true
        github_token: ${{ inputs.github_token || github.token }}
        publish_branch: ${{ inputs.github_branch }}
        publish_dir: output
branding:
  color: blue
  icon: download-cloud
